# Generated by Django 4.0.6 on 2022-07-17 09:26

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyTortoiseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planName', models.CharField(max_length=200, verbose_name='Plan Name')),
                ('amountOptions', multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Debit cards'), (3, 'Electronic bank transfers'), (1, 'Credit cards'), (2, 'Mobile payments')], max_length=3)),
                ('tenureOptions', multiselectfield.db.fields.MultiSelectField(choices=[(0, 'weekly'), (1, 'fortnightly'), (2, 'quarterly')], max_length=3)),
                ('benefitPercentage', models.IntegerField()),
                ('benefitType', multiselectfield.db.fields.MultiSelectField(choices=[(0, 'cashback'), (1, 'extraVoucher')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotionName', models.CharField(max_length=200, verbose_name='Promotion Name')),
                ('benefitPercentage', models.IntegerField()),
                ('userCount', models.IntegerField(default=10)),
                ('duration', models.IntegerField(default=20)),
                ('planName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.plan')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plans', models.ManyToManyField(blank=True, to='plans.plan')),
                ('user', models.ManyToManyField(blank=True, to='plans.mytortoiseuser')),
            ],
        ),
    ]
