# Generated by Django 4.0.6 on 2022-07-17 12:45

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customergoal',
            name='benefitPercentage',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='plan',
            name='amountOptions',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(2, 'Mobile payments'), (1, 'Credit cards'), (0, 'Debit cards'), (3, 'Electronic bank transfers')], max_length=3),
        ),
    ]
